import type { BlogPost } from "./posts";

// Keyword-targeted SEO posts — batch 8: Watermark Remover, Batch Editor (5 each).
// Hero images are committed under public/blog-heroes/<slug>.jpg.

const P = (
  slug: string, title: string, metaTitle: string, metaDescription: string, excerpt: string,
  date: string, category: string, keywords: string[], toolHref: string, toolLabel: string,
  sections: { heading?: string; body: string }[],
): BlogPost => ({ slug, title, metaTitle, metaDescription, excerpt, date, readTime: "8 min read", category, keywords, toolHref, toolLabel, image: `/blog-heroes/${slug}.jpg`, sections });

const FAQ = (pairs: [string, string][]) => pairs.map(([q, a]) => `**${q}**\n${a}`).join("\n\n");

export const SEO_POSTS_8: BlogPost[] = [
  // ─────────────── WATERMARK REMOVER ───────────────
  P(
    "how-to-remove-a-watermark-from-a-picture-online",
    "How to Remove a Watermark From a Picture Online (Free)",
    "Remove a Watermark From a Picture Online — Free | JPT AI",
    "Learn how to remove a watermark from a picture online free with AI — no software, no download. Erase logos, text and stamps.",
    "No software needed — remove a watermark from a picture right in your browser with AI. Here's how, free.",
    "2026-07-22", "Guide",
    ["remove watermark from picture online", "online watermark remover", "remove watermark online free", "watermark remover"],
    "/watermark-remover", "Remove Watermark →",
    [
      { body: `You don't need to install anything to **remove a watermark from a picture** — an AI watermark remover works right in your browser. Upload the image, and it rebuilds what was behind the mark. Here's how to remove a watermark online, free, and when it works best.` },
      { heading: "Why online beats software", body: `Desktop watermark tools mean downloads, installs and often a licence fee. An **online AI remover** needs none of that — it runs in the browser on any device, detects the mark, and reconstructs the area behind it. Nothing to install, nothing to uninstall.` },
      { heading: "How to remove a watermark online (free)", body: `**Step 1 — Open sjpt.io/watermark-remover.**\n\n**Step 2 — Upload your picture.**\n\n**Step 3 — Click Remove Watermark** — the AI rebuilds what the mark covered.\n\n**Step 4 — Download** the clean image.\n\nFree to try, no software.` },
      { heading: "Where it works best", body: `Marks over **simple or blurred backgrounds** (sky, walls, bokeh) clean up most convincingly; heavy detail directly under the mark is the hardest case. Start from the **highest-quality copy** — the more detail the AI has, the better the fill.` },
      { heading: "Only on images you own", body: `Remove watermarks from pictures you **own or are licensed to edit** — your own photos, a mark you added by mistake, a properly-licensed asset. Don't strip a watermark from copyrighted work to reuse it without permission.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I remove a watermark from a picture online?", "Open the AI watermark remover, upload your picture, click Remove, and download. Free, no software."],
        ["Do I need to install anything?", "No — it runs in your browser on any device."],
        ["When does it work best?", "On marks over simple or blurred backgrounds; heavy detail under the mark is harder."],
        ["Is it okay to remove any watermark?", "Only from images you own or are licensed to edit — not others' copyrighted work."],
      ]) },
      { heading: "Key takeaways", body: `An online AI remover clears watermarks in the browser — best on simple backgrounds, and only on images you own. Try it free at sjpt.io/watermark-remover. Remove Watermark →` },
    ],
  ),
  P(
    "how-to-remove-a-date-stamp-from-a-photo",
    "How to Remove a Date Stamp From a Photo (Free)",
    "How to Remove a Date Stamp From a Photo — Free | JPT AI",
    "Learn how to remove a date/time stamp from a photo free with AI — erase the burned-in date cleanly. No software, no sign-up.",
    "That orange date stamp in the corner? AI can rebuild the photo behind it. Here's how to remove a date stamp, free.",
    "2026-07-22", "Guide",
    ["remove date stamp from photo", "remove date from photo", "remove timestamp from photo", "delete date stamp"],
    "/watermark-remover", "Remove Date Stamp →",
    [
      { body: `Old cameras (and some phone apps) burn an **orange date/time stamp** into the corner of photos — charming once, distracting now. Because it's baked into the pixels, you can't just toggle it off; you rebuild what's behind it. AI does exactly that. Here's how to remove a date stamp from a photo, free.` },
      { heading: "Why the date is 'stuck'", body: `A burned-in date stamp is **part of the image**, not metadata you can switch off — the camera drew it onto the photo. Removing it means reconstructing the pixels it covered, which is what AI inpainting is built for.` },
      { heading: "How to remove a date stamp (free)", body: `**Step 1 — Open sjpt.io/watermark-remover** (it handles date stamps too).\n\n**Step 2 — Upload your photo.**\n\n**Step 3 — Click Remove** — the AI rebuilds the area under the date.\n\n**Step 4 — Download** the clean photo.\n\nFree to try, no software.` },
      { heading: "Best results", body: `Date stamps usually sit in a **corner over a fairly plain area** — which is the easy case, so results are often flawless. If the stamp overlaps busy detail, expect a good result that may need a light touch-up. Start from the best copy you have.` },
      { heading: "Turn it off for future photos", body: `To stop new photos getting a stamp, check your **camera/app settings** for a "date stamp" or "timestamp" toggle and switch it off. The date is still saved in the photo's metadata, just not drawn onto the image.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I remove a date stamp from a photo?", "Upload it to the AI remover, click Remove, and download — it rebuilds the area under the date. Free."],
        ["Why can't I just turn the date off?", "It's burned into the pixels, not metadata. Removing it means reconstructing what's behind it."],
        ["Will it look natural?", "Usually yes — date stamps sit over plain corners, which clean up cleanly."],
        ["How do I stop future date stamps?", "Turn off the date/timestamp setting in your camera or photo app."],
      ]) },
      { heading: "Key takeaways", body: `A burned-in date stamp is pixels, not metadata — AI rebuilds the corner behind it cleanly. Do it free at sjpt.io/watermark-remover, and switch the stamp off for future shots. Remove Date Stamp →` },
    ],
  ),
  P(
    "how-to-remove-an-object-from-a-photo",
    "How to Remove an Object From a Photo (Free, AI)",
    "How to Remove an Object From a Photo — Free | JPT AI",
    "Learn how to remove an unwanted object from a photo free with AI — erase photobombers, clutter and distractions. No software, no sign-up.",
    "A photobomber or bit of clutter can ruin a great shot. Here's how AI removes an unwanted object cleanly, free.",
    "2026-07-23", "Guide",
    ["remove object from photo", "remove unwanted object", "erase object from picture", "remove photobomber"],
    "/watermark-remover", "Remove Object Free →",
    [
      { body: `A **photobomber**, a stray bin, a distracting sign — one unwanted object can spoil an otherwise great photo. AI can erase it and rebuild the background so it looks like it was never there. Here's how to remove an object from a photo, free.` },
      { heading: "How object removal works", body: `The AI **reconstructs the background** where the object was, matching the surrounding texture, colour and lighting — the same inpainting that powers watermark removal. On clean, continuous backgrounds the result is often invisible.` },
      { heading: "How to remove an object (free)", body: `**Step 1 — Open sjpt.io/watermark-remover** (it removes objects and marks alike).\n\n**Step 2 — Upload your photo.**\n\n**Step 3 — Remove** the unwanted area — the AI fills it from the surroundings.\n\n**Step 4 — Download** the clean photo.\n\nFree to try, no software.` },
      { heading: "What removes cleanly (and what's hard)", body: `**Easy:** objects over sky, water, grass, walls or blur — the background is predictable. **Harder:** objects overlapping faces, fine patterns or another subject, where the AI has less to go on. For tricky cases, expect a good result that may want a light touch-up.` },
      { heading: "Tips for a clean removal", body: `Start from the **highest-quality photo**. Remove **one thing at a time** for the cleanest fill. If a large object sits over busy detail, it's the toughest case — smaller, contained objects over simple areas vanish best.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I remove an object from a photo for free?", "Upload it to the AI remover, remove the unwanted area, and download — the AI rebuilds the background. Free."],
        ["What removes cleanly?", "Objects over sky, water, grass, walls or blur clean up best; overlaps with faces or patterns are harder."],
        ["Can it remove a photobomber?", "Yes — especially over a simple background; over fine detail it may need a touch-up."],
        ["Do I need software?", "No — it runs in your browser, free to try."],
      ]) },
      { heading: "Key takeaways", body: `AI removes an unwanted object by rebuilding the background — cleanest over simple areas, one object at a time. Free at sjpt.io/watermark-remover. Remove Object Free →` },
    ],
  ),
  P(
    "how-to-remove-a-watermark-from-a-screenshot",
    "How to Remove a Watermark From a Screenshot (Free)",
    "Remove a Watermark From a Screenshot — Free | JPT AI",
    "Learn how to remove a watermark from a screenshot free with AI — clear app overlays, banners and stamps. No software, no sign-up.",
    "Screenshots often carry an app watermark or banner. Here's how to clean one up with AI, free.",
    "2026-07-23", "Guide",
    ["remove watermark from screenshot", "clean screenshot watermark", "remove overlay from screenshot", "screenshot watermark remover"],
    "/watermark-remover", "Remove Watermark →",
    [
      { body: `Screenshots from certain apps arrive with a **watermark, banner or overlay** stamped on top. If it's your own content you want to tidy, an AI remover can rebuild what's behind the mark. Here's how to remove a watermark from a screenshot, free — and when it's appropriate.` },
      { heading: "Screenshot marks vs. photo marks", body: `Screenshot overlays are often **flat colour over flat UI**, which can be the *easiest* case for AI to rebuild — clean edges, predictable background. The tool detects the mark and reconstructs the interface or image beneath it.` },
      { heading: "How to remove it (free)", body: `**Step 1 — Open sjpt.io/watermark-remover.**\n\n**Step 2 — Upload your screenshot.**\n\n**Step 3 — Click Remove** — the AI rebuilds the area under the mark.\n\n**Step 4 — Download** the clean screenshot.\n\nFree to try, no software.` },
      { heading: "Crop as an alternative", body: `If the watermark sits at the **edge** of the screenshot, the quickest fix is simply to **crop it off** — no reconstruction needed. Use the remover when the mark is *within* the content you need to keep.` },
      { heading: "Keep it fair", body: `Clean up **your own** screenshots and content. Don't remove watermarks to pass off a paid or copyrighted app's output as unmarked when the mark is there to denote a licence — use it responsibly on content you're entitled to edit.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I remove a watermark from a screenshot?", "Upload it to the AI remover, click Remove, and download. Or, if the mark is at the edge, just crop it off. Free."],
        ["Is it easy for AI?", "Often yes — flat overlays over flat UI rebuild cleanly."],
        ["Should I crop instead?", "If the mark is at the edge, cropping is the fastest fix."],
        ["Is it okay to remove it?", "Use it on your own content; don't strip marks that denote someone else's licence."],
      ]) },
      { heading: "Key takeaways", body: `AI cleans watermarks from screenshots (flat overlays rebuild easily) — or just crop an edge mark. Use it on your own content. Free at sjpt.io/watermark-remover. Remove Watermark →` },
    ],
  ),
  P(
    "how-to-remove-a-watermark-from-ai-generated-images",
    "How to Remove a Watermark From AI-Generated Images (Free)",
    "Remove Watermark From AI Images — Free Online | JPT AI",
    "Learn how to remove a watermark from your AI-generated images free — clear the small corner logo some tools add. No software, no sign-up.",
    "Some AI image tools stamp a small logo on outputs. Here's how to clean your own generations, free.",
    "2026-07-24", "Guide",
    ["remove watermark from ai image", "remove ai watermark", "ai generated image watermark", "clean ai image"],
    "/watermark-remover", "Remove Watermark →",
    [
      { body: `Some AI image generators add a **small corner logo or watermark** to their outputs. If you generated the image and your plan allows a clean version, an AI remover can tidy it up. Here's how to remove a watermark from AI-generated images, free — plus the rights to check first.` },
      { heading: "Check your rights first", body: `Before removing anything, check the **generator's terms and your licence**. Many tools grant you full rights to your generations (sometimes only on paid tiers) and the corner logo is just branding you may clear; others require attribution. Remove marks only where your licence permits.` },
      { heading: "How to remove it (free)", body: `**Step 1 — Open sjpt.io/watermark-remover.**\n\n**Step 2 — Upload your AI image.**\n\n**Step 3 — Click Remove** — the AI rebuilds the small area under the logo.\n\n**Step 4 — Download** the clean image.\n\nFree to try, no software.` },
      { heading: "Why it usually cleans well", body: `These logos are typically **small and in a corner**, often over a fairly plain part of the image — the easy case for AI inpainting. The result is usually seamless, since there's little detail to reconstruct.` },
      { heading: "Or just crop it", body: `Because the mark is usually a **corner logo**, cropping a sliver off the edge is often the simplest fix and loses very little of the image. Use the remover when you'd rather keep the full frame.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I remove a watermark from an AI image?", "Upload it to the AI remover, click Remove, and download — or crop the corner logo off. Free."],
        ["Am I allowed to remove it?", "Check the generator's terms/licence — many grant full rights to your generations, some require attribution."],
        ["Does it clean up well?", "Usually — corner logos over plain areas are the easy case for AI."],
        ["Is cropping easier?", "Often yes, since the logo sits in a corner — cropping loses very little."],
      ]) },
      { heading: "Key takeaways", body: `Check your licence, then clear a small corner logo from your own AI images with AI (or just crop it). Free at sjpt.io/watermark-remover. Remove Watermark →` },
    ],
  ),

  // ─────────────── BATCH EDITOR ───────────────
  P(
    "how-to-resize-multiple-images-at-once",
    "How to Resize Multiple Images at Once (Free, Bulk)",
    "How to Resize Multiple Images at Once — Free | JPT AI",
    "Learn how to resize multiple images at once free — bulk-resize a whole folder to the same dimensions in your browser. No sign-up.",
    "Resizing photos one by one is a chore. Here's how to bulk-resize many images at once, free.",
    "2026-07-24", "Guide",
    ["resize multiple images at once", "bulk resize images", "batch resize photos", "resize many images"],
    "/batch-editor", "Bulk Resize Free →",
    [
      { body: `Resizing photos **one at a time** is tedious when you have dozens. A batch editor resizes them **all at once** to the same dimensions — perfect for web galleries, product sets and uploads. Here's how to resize multiple images at once, free.` },
      { heading: "Why bulk resize", body: `Consistent sizing looks **professional** (a gallery where every image matches) and saves huge time. Uploading a folder of full-resolution phone photos is slow and often over the limit; resizing the whole set first fixes both at once.` },
      { heading: "How to resize in bulk (free)", body: `**Step 1 — Open the batch editor** at sjpt.io/batch-editor.\n\n**Step 2 — Add all your images.**\n\n**Step 3 — Choose Resize** and set the target dimensions.\n\n**Step 4 — Run and download** the whole set.\n\nProcessed in your browser.` },
      { heading: "Pick the right size", body: `**Web galleries:** 1200–1600px wide. **Thumbnails:** 400–600px. **Profile sets:** 400×400 square. Keep proportions locked so nothing stretches. Resize once, apply to all.` },
      { heading: "Resize then compress", body: `For the lightest, fastest set, **resize and compress together** — the batch editor can do both in one pass, so your whole folder comes out right-sized and web-ready.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I resize multiple images at once for free?", "Open JPT AI's batch editor, add your images, choose Resize with target dimensions, and run. Free."],
        ["Will it keep proportions?", "Yes — lock the aspect ratio so images scale without stretching."],
        ["Can I resize and compress together?", "Yes — apply both in one pass for the lightest, web-ready set."],
        ["Is it private?", "Yes — processed in your browser."],
      ]) },
      { heading: "Key takeaways", body: `Bulk-resize a whole folder to matching dimensions in one pass — lock proportions and combine with compression for web-ready sets. Free at sjpt.io/batch-editor. Bulk Resize Free →` },
    ],
  ),
  P(
    "how-to-compress-multiple-images-at-once",
    "How to Compress Multiple Images at Once (Free, Bulk)",
    "How to Compress Multiple Images at Once — Free | JPT AI",
    "Learn how to compress multiple images at once free — shrink a whole folder for faster uploads and lighter pages. No sign-up.",
    "Compressing photos one by one wastes time. Here's how to bulk-compress many images at once, free.",
    "2026-07-25", "Guide",
    ["compress multiple images at once", "bulk compress images", "batch compress photos", "compress many images"],
    "/batch-editor", "Bulk Compress Free →",
    [
      { body: `Got a folder of heavy photos to lighten? Compressing them **one at a time** is a slog. A batch editor compresses them **all at once**, so a whole set gets smaller in a single pass — ideal for websites, email and uploads. Here's how, free.` },
      { heading: "Why compress in bulk", body: `Lighter images mean **faster pages, quicker uploads and smaller emails** — and doing a whole folder together saves you repeating the same task dozens of times. One setting, applied to every image.` },
      { heading: "How to bulk compress (free)", body: `**Step 1 — Open the batch editor** at sjpt.io/batch-editor.\n\n**Step 2 — Add all your images.**\n\n**Step 3 — Choose Compress** (set quality or a target size).\n\n**Step 4 — Run and download** the whole set.\n\nProcessed in your browser.` },
      { heading: "Resize first for the biggest win", body: `If the images are much larger than needed, **resize the set first**, then compress. Fewer pixels plus compression gives the smallest files — often 80–90% lighter with no visible change.` },
      { heading: "Common uses", body: `**Website galleries** — fast-loading, SEO-friendly. **Email batches** — send many without hitting limits. **Marketplace listings** — meet size caps across a set. **Cloud storage** — fit more in less space.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I compress multiple images at once for free?", "Open JPT AI's batch editor, add your images, choose Compress, and run. Free, in your browser."],
        ["Will quality drop?", "Not visibly at sensible settings — the change is invisible while files shrink a lot."],
        ["Should I resize too?", "Yes — resizing oversized images first gives the smallest files."],
        ["Is there a limit?", "It's free and handles large batches in the browser."],
      ]) },
      { heading: "Key takeaways", body: `Bulk-compress a whole folder in one pass (resize first for the biggest saving) — lighter files for faster pages and easier uploads. Free at sjpt.io/batch-editor. Bulk Compress Free →` },
    ],
  ),
  P(
    "how-to-convert-multiple-images-at-once",
    "How to Convert Multiple Images at Once (Free, Bulk)",
    "How to Convert Multiple Images at Once — Free | JPT AI",
    "Learn how to convert multiple images at once free — batch-convert a folder to JPG, PNG or WebP in your browser. No sign-up.",
    "Converting images one by one is slow. Here's how to bulk-convert a whole folder to JPG, PNG or WebP, free.",
    "2026-07-25", "Guide",
    ["convert multiple images at once", "bulk convert images", "batch convert photos", "convert many images"],
    "/batch-editor", "Bulk Convert Free →",
    [
      { body: `Need a folder of images all in the **same format**? Converting them individually is a waste of time. A batch editor converts them **all at once** — to JPG, PNG or WebP — in a single pass. Here's how to convert multiple images at once, free.` },
      { heading: "Why bulk convert", body: `Maybe a system only accepts **JPG**, you want **WebP** to speed up a site, or you need **PNG** for transparency across a set. Whatever the reason, converting the whole folder together is far faster than one file at a time — and keeps the set consistent.` },
      { heading: "How to bulk convert (free)", body: `**Step 1 — Open the batch editor** at sjpt.io/batch-editor.\n\n**Step 2 — Add all your images.**\n\n**Step 3 — Choose Convert** and pick the output format (JPG · PNG · WebP).\n\n**Step 4 — Run and download** the converted set.\n\nProcessed in your browser.` },
      { heading: "Pick the right format", body: `**JPG** for photos (small, universal). **WebP** for the web (smallest, keeps transparency). **PNG** for graphics needing transparency or sharp edges. Convert the whole set to whichever the job needs.` },
      { heading: "Convert then compress", body: `Converting to WebP already shrinks files; add a **compress** step in the same pass for the lightest web-ready set. One run, right format, right size.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I convert multiple images at once for free?", "Open JPT AI's batch editor, add your images, choose Convert and a format, and run. Free."],
        ["Which formats can I convert to?", "JPG, PNG and WebP — pick per the job."],
        ["Can I convert and compress together?", "Yes — apply both in one pass for a light, consistent set."],
        ["Is it private?", "Yes — processed in your browser."],
      ]) },
      { heading: "Key takeaways", body: `Bulk-convert a folder to JPG, PNG or WebP in one pass — add compression for a light, consistent, web-ready set. Free at sjpt.io/batch-editor. Bulk Convert Free →` },
    ],
  ),
  P(
    "how-to-watermark-multiple-photos-at-once",
    "How to Watermark Multiple Photos at Once (Free, Bulk)",
    "How to Watermark Multiple Photos at Once — Free | JPT AI",
    "Learn how to watermark multiple photos at once free — brand a whole shoot or set with the same mark in one pass. No sign-up.",
    "Watermarking photos one by one is painful. Here's how to watermark a whole set at once, free.",
    "2026-07-26", "Guide",
    ["watermark multiple photos at once", "bulk watermark photos", "batch watermark", "watermark many images"],
    "/batch-editor", "Bulk Watermark Free →",
    [
      { body: `Branding a **whole shoot or product set** with a watermark, one photo at a time, is soul-destroying. A batch editor applies the **same watermark to every image at once** — consistent placement, zero repetition. Here's how to watermark multiple photos at once, free.` },
      { heading: "Why bulk watermark", body: `Consistency matters: the **same mark, same spot** across a gallery looks professional and reinforces your brand. And doing 50 photos in one pass instead of 50 separate edits saves real time — essential for photographers and sellers.` },
      { heading: "How to bulk watermark (free)", body: `**Step 1 — Open the batch editor** at sjpt.io/batch-editor.\n\n**Step 2 — Add all your photos.**\n\n**Step 3 — Choose Watermark**, set your text, opacity and position.\n\n**Step 4 — Run and download** the whole branded set.\n\nProcessed in your browser.` },
      { heading: "Keep it subtle and consistent", body: `Use a **semi-transparent** mark in a **consistent corner** so it brands without distracting. Set it once; it applies identically to every image. A tasteful, uniform watermark makes a set look like a proper portfolio.` },
      { heading: "Combine with resize/compress", body: `Preparing a web gallery? **Resize, compress and watermark** the whole set in one pass — every image comes out branded, right-sized and web-ready together.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I watermark multiple photos at once for free?", "Open JPT AI's batch editor, add your photos, choose Watermark, set the text and position, and run. Free."],
        ["Will the watermark be consistent?", "Yes — the same mark and placement apply to every image."],
        ["Can I resize and watermark together?", "Yes — combine resize, compress and watermark in one pass."],
        ["Is it private?", "Yes — processed in your browser."],
      ]) },
      { heading: "Key takeaways", body: `Watermark a whole set at once with consistent, subtle branding — combine with resize/compress for web-ready galleries. Free at sjpt.io/batch-editor. Bulk Watermark Free →` },
    ],
  ),
  P(
    "how-to-bulk-edit-photos",
    "How to Bulk Edit Photos (Resize, Compress, Convert & More)",
    "How to Bulk Edit Photos — Free Online | JPT AI",
    "Learn how to bulk edit photos free — apply resize, compress, convert, crop, rotate and watermark to a whole folder at once. No sign-up.",
    "Editing photos one by one doesn't scale. Here's how to bulk edit a whole folder in one pass, free.",
    "2026-07-26", "Guide",
    ["bulk edit photos", "batch edit photos", "edit multiple photos at once", "bulk photo editor"],
    "/batch-editor", "Bulk Edit Free →",
    [
      { body: `When you've got a **whole folder** to process, editing photos individually doesn't scale. A batch editor applies the same steps — **resize, compress, convert, crop, rotate, watermark** — to every image at once. Here's how to bulk edit photos, free.` },
      { heading: "What you can bulk apply", body: `In one pass you can **resize** to matching dimensions, **compress** for lighter files, **convert** to JPG/PNG/WebP, **crop** to a ratio, **rotate/flip**, and **watermark** the whole set. Stack several steps and they all apply to every image together.` },
      { heading: "How to bulk edit (free)", body: `**Step 1 — Open the batch editor** at sjpt.io/batch-editor.\n\n**Step 2 — Add all your photos.**\n\n**Step 3 — Pick the steps** (e.g. resize + compress + watermark) and set their options.\n\n**Step 4 — Run and download** the finished set.\n\nProcessed in your browser.` },
      { heading: "A typical web-ready recipe", body: `For a website gallery: **crop to a consistent ratio → resize to display width → compress → convert to WebP**. Run once, and the whole folder comes out uniform, light and fast-loading — a job that would take ages one by one.` },
      { heading: "Why it's private and free", body: `Everything runs **in your browser**, so your photos never leave your device — quick, private and free, with no per-image limits to slow you down. Great for photographers, sellers and anyone with a lot of images.` },
      { heading: "Frequently asked questions", body: FAQ([
        ["How do I bulk edit photos for free?", "Open JPT AI's batch editor, add your photos, pick the steps (resize, compress, convert, crop, rotate, watermark), and run. Free."],
        ["Can I apply several edits at once?", "Yes — stack steps and they all apply to every image in one pass."],
        ["Is a whole folder supported?", "Yes — add many images and process them together."],
        ["Is it private?", "Yes — everything runs in your browser; photos don't leave your device."],
      ]) },
      { heading: "Key takeaways", body: `Bulk edit a whole folder — resize, compress, convert, crop, rotate, watermark — in one private, browser-based pass. Free at sjpt.io/batch-editor. Bulk Edit Free →` },
    ],
  ),
];
