/**
 * app-creatives.ts — where an AI app's example photos come from.
 *
 * Two sources, in order:
 *
 *   1. `public/creatives/<slug>-{before,after}.webp`, committed to the repo
 *      and added with `npm run creative` — see docs/creatives.md. These are
 *      the hand-made ones.
 *   2. The Supabase bucket, where the bulk-generated set lives.
 *
 * A local file wins because someone looked at it and decided it was good.
 * Missing from both is a normal state rather than an error: ExampleImage and
 * SmartImage draw the app's own placeholder artwork instead of a broken image.
 *
 * MANIFEST is generated by the script — do not edit it by hand. A build-time
 * list rather than a filesystem check, because the pages that read it also
 * render on surfaces that cannot touch the filesystem, and because a name that
 * does not match is then caught when the image is added rather than by a
 * visitor.
 */

/** slug → which halves exist on disk. Generated; see scripts/add-creative.mjs. */
export const MANIFEST: Record<string, { before?: true; after?: true }> = {
  /* GENERATED:START */
  /* GENERATED:END */
};

export function localBefore(slug: string): string | null {
  return MANIFEST[slug]?.before ? `/creatives/${slug}-before.webp` : null;
}

export function localAfter(slug: string): string | null {
  return MANIFEST[slug]?.after ? `/creatives/${slug}-after.webp` : null;
}

/** How many apps have a hand-made example. */
export function localCreativeCount(): { apps: number; before: number; after: number } {
  const keys = Object.keys(MANIFEST);
  return {
    apps: keys.length,
    before: keys.filter((k) => MANIFEST[k].before).length,
    after: keys.filter((k) => MANIFEST[k].after).length,
  };
}


/* ────────────────────────────────────────────────────────────────────────────
   Uploaded creatives
   ──────────────────────────────────────────────────────────────────────── */

import { isRenderable } from "@/lib/image-hosts";

const BUCKET = "landing";

/**
 * Where /admin/creatives puts what you upload.
 *
 * Supabase rather than the repo, because this path has to work without a
 * deploy: upload, reload, done. The repo path (npm run creative) stays for
 * images that arrive in a session, but it costs two minutes and a push, and
 * that is a bad trade when you are doing two hundred of them.
 */
export function uploadedCreative(slug: string, half: "before" | "after"): string {
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
  return `${base}/storage/v1/object/public/${BUCKET}/creatives/${slug}-${half}.webp`;
}

/**
 * Every place an example might live, best first.
 *
 * Returned as a list rather than resolved here because nothing on the server
 * knows which of these exist — the bucket is not queried at build time and a
 * HEAD request per app per render would be absurd. The browser finds out the
 * only way it can: it tries one, and moves to the next when the load fails.
 * The last rung is the app's own placeholder artwork, so the bottom of the
 * list is never a broken image.
 */
export function creativeSources(slug: string, half: "before" | "after", legacy?: string | null): string[] {
  const out: string[] = [];
  const local = half === "before" ? localBefore(slug) : localAfter(slug);
  if (local) out.push(local);
  out.push(uploadedCreative(slug, half));
  if (legacy) out.push(legacy);
  return out.filter(isRenderable);
}
