/**
 * app-creatives.ts — where an AI app's example photos come from.
 *
 * Two sources, in order:
 *
 *   1. `public/creatives/<slug>-{before,after}.webp`, committed to the repo
 *      and added with `npm run creative` — see docs/creatives.md. These are
 *      the hand-made ones.
 *   2. The Supabase bucket, where the bulk-generated set lives.
 *
 * A local file wins because someone looked at it and decided it was good.
 * Missing from both is a normal state rather than an error: ExampleImage and
 * SmartImage draw the app's own placeholder artwork instead of a broken image.
 *
 * MANIFEST is generated by the script — do not edit it by hand. A build-time
 * list rather than a filesystem check, because the pages that read it also
 * render on surfaces that cannot touch the filesystem, and because a name that
 * does not match is then caught when the image is added rather than by a
 * visitor.
 */

/** slug → which halves exist on disk. Generated; see scripts/add-creative.mjs. */
export const MANIFEST: Record<string, { before?: true; after?: true }> = {
  /* GENERATED:START */
  /* GENERATED:END */
};

export function localBefore(slug: string): string | null {
  return MANIFEST[slug]?.before ? `/creatives/${slug}-before.webp` : null;
}

export function localAfter(slug: string): string | null {
  return MANIFEST[slug]?.after ? `/creatives/${slug}-after.webp` : null;
}

/** How many apps have a hand-made example. */
export function localCreativeCount(): { apps: number; before: number; after: number } {
  const keys = Object.keys(MANIFEST);
  return {
    apps: keys.length,
    before: keys.filter((k) => MANIFEST[k].before).length,
    after: keys.filter((k) => MANIFEST[k].after).length,
  };
}
