import { CREATIVE_APPS, type CreativeApp } from "@/lib/creative-apps";

export type GrowthPage = {
  slug:string; title:string; description:string; h1:string; intro:string;
  appSlugs:string[]; bullets:string[]; faqs:{q:string;a:string}[];
};

export const USE_CASES: GrowthPage[] = [
 {slug:"social-media",title:"AI Image Tools for Social Media | Pixel Shine",description:"Create profile photos, Instagram images, thumbnails, aesthetic edits and social-ready visuals with Pixel Shine AI.",h1:"AI Image Tools for Social Media",intro:"Create scroll-stopping social visuals from the photos you already have. Use one-tap AI apps for profile pictures, aesthetics, fashion, thumbnails and viral photo styles.",appSlugs:["profile-picture-maker","facebook-pfp-maker","instagram-photo-editor","youtube-thumbnail-generator","aesthetic-photo-editor","ai-selfie-generator"],bullets:["Profile pictures that stay recognizable at small sizes","Instagram-ready edits and aesthetic styles","YouTube thumbnails and creator visuals","Fast photo trends without learning prompts"],faqs:[{q:"What can I make for social media?",a:"Pixel Shine includes profile-picture, Instagram, YouTube thumbnail, aesthetic and photo-style tools. Choose an app, upload a photo and generate a result on the page."},{q:"Do I need design software?",a:"No. The creative apps are browser-based and use preset instructions, so you can start from a photo instead of building an edit from scratch."}]},
 {slug:"linkedin",title:"AI LinkedIn Photo & Headshot Tools | Pixel Shine",description:"Turn a selfie into a polished LinkedIn or professional headshot with Pixel Shine AI.",h1:"AI LinkedIn Photo & Headshot Tools",intro:"Create professional profile photos from an existing selfie. Compare several headshot styles for LinkedIn, business profiles, applications and team pages.",appSlugs:["linkedin-headshot","professional-headshot","business-headshot","ceo-headshot","lawyer-headshot","doctor-headshot"],bullets:["LinkedIn-ready head-and-shoulders framing","Corporate, executive and business styles","Professional backgrounds and lighting","Use one selfie as the starting point"],faqs:[{q:"Can I make a LinkedIn headshot from a selfie?",a:"Yes. Upload a clear selfie to the LinkedIn Headshot Maker or Professional Headshot Maker and generate a polished portrait."},{q:"What photo works best?",a:"Use a clear, well-lit photo where your face is visible. Front-facing images generally give the most predictable result."}]},
 {slug:"ecommerce",title:"AI Product Photography Tools for Ecommerce | Pixel Shine",description:"Create cleaner product photos, catalogue visuals, backgrounds and marketing images with Pixel Shine.",h1:"AI Product Photography Tools for Ecommerce",intro:"Turn ordinary product photos into cleaner catalogue and marketing assets. Use background, product and enhancement tools without rebuilding the shoot from scratch.",appSlugs:["product-photo-editor","product-background-remover","product-background-generator","product-shadow-generator","jewelry-photo-editor","fashion-product-photo"],bullets:["Clean product backgrounds","Catalogue-ready product compositions","Jewelry and fashion product edits","Better detail and presentation from existing photos"],faqs:[{q:"Can Pixel Shine edit product photos?",a:"Yes. The product-focused apps are designed for backgrounds, product presentation, jewelry, fashion and image enhancement."},{q:"Do I need a studio photo?",a:"A sharp original photo is the best starting point. AI can change the presentation, but it cannot recover detail that was never captured."}]},
 {slug:"real-estate",title:"AI Real Estate Photo Editing Tools | Pixel Shine",description:"Enhance property photos, interiors, backgrounds and real-estate marketing visuals with Pixel Shine AI.",h1:"AI Real Estate Photo Editing Tools",intro:"Prepare property images for listings and marketing with AI-assisted edits for rooms, exteriors, backgrounds and presentation.",appSlugs:["real-estate-photo-editor","house-photo-editor","interior-photo-editor","room-design","architecture-photo-editor","background-changer"],bullets:["Improve listing-photo presentation","Redesign or restyle interiors","Change distracting backgrounds","Create consistent property visuals"],faqs:[{q:"What real-estate photos can I edit?",a:"Pixel Shine has apps for house photos, interiors, rooms, architecture and background changes. Start with the closest matching app and upload the original image."},{q:"Will the property geometry stay the same?",a:"Results depend on the requested transformation. For accurate listings, use prompts that ask the model to preserve structure and perspective."}]},
 {slug:"photography",title:"AI Photo Editing Tools for Photographers | Pixel Shine",description:"Restore, sharpen, enhance, retouch and restyle photos with Pixel Shine AI creative tools.",h1:"AI Photo Editing Tools for Photographers",intro:"Use AI for common finishing tasks while keeping the original photo as the starting point: restoration, enhancement, retouching, background work and creative styles.",appSlugs:["restore-old-photos","image-sharpener","unblur-image","denoise-image","old-photo-restoration","ai-photo-enhancer"],bullets:["Restore older photographs","Recover clarity from soft images","Reduce noise and improve detail","Create alternate creative treatments"],faqs:[{q:"Can AI improve an old photograph?",a:"Yes. Restoration and enhancement apps can reduce visible damage, noise and softness. The original scan or photo quality still affects the result."},{q:"Can I keep the original photo?",a:"Yes. The generator works from an uploaded copy; your original file is not replaced by the generated result."}]},
 {slug:"creators",title:"AI Image Tools for Content Creators | Pixel Shine",description:"Create thumbnails, profile images, photoshoots, outfits and social visuals for creator content with Pixel Shine.",h1:"AI Image Tools for Content Creators",intro:"Move from one source photo to multiple creator-ready visuals: thumbnails, profile images, photoshoots, outfits and social edits.",appSlugs:["youtube-thumbnail-generator","ai-photoshoot","outfit-generator","profile-picture-maker","facebook-pfp-maker","instagram-photo-editor"],bullets:["Thumbnail concepts from your photos","Creator profile images","AI photoshoot variations","Outfit and social-content edits"],faqs:[{q:"What can creators make with Pixel Shine?",a:"Creators can make thumbnails, profile pictures, photoshoot variations, outfit edits and social images from uploaded photos."},{q:"Do I need to write prompts?",a:"The creative apps use preset transformations. You can select the app and options without writing a prompt from scratch."}]},
 {slug:"weddings",title:"AI Wedding & Pre-Wedding Photo Tools | Pixel Shine",description:"Create couple portraits, pre-wedding looks, festive portraits and polished wedding visuals with Pixel Shine AI.",h1:"AI Wedding & Pre-Wedding Photo Tools",intro:"Explore AI-assisted couple and portrait styles for wedding, pre-wedding, anniversary and festive photography.",appSlugs:["couple-photoshoot","anniversary-photo-editor","festival-photoshoot","saree-photoshoot","saree-photo-editor","fashion-photo-editor"],bullets:["Pre-wedding portrait concepts","Couple and anniversary looks","Traditional and festive styles","Saree and fashion transformations"],faqs:[{q:"Can I create a pre-wedding photo with AI?",a:"Yes. Upload a couple photo and use the Couple Photoshoot Maker or related portrait apps for a styled result."},{q:"What should I upload?",a:"Use a clear photo where the faces are visible and well lit. For couple tools, both faces should be reasonably unobstructed."}]},
];

export const ANSWER_PAGES: GrowthPage[] = [
 {slug:"ai-image-editor",title:"AI Image Editor Online | Pixel Shine",description:"Edit photos with AI prompts, creative apps, background tools, enhancement and one-tap transformations in Pixel Shine.",h1:"AI Image Editor Online",intro:"Pixel Shine combines an AI editor with focused one-tap creative apps, so you can either describe an edit or choose a specific transformation.",appSlugs:["ai-editor","ai-photoshoot","background-changer","image-sharpener","remove-object"],bullets:["Describe an edit in plain language","Choose a focused creative app","Upload and compare the result","Continue into related image tools"],faqs:[{q:"What is an AI image editor?",a:"An AI image editor lets you describe or select image transformations and uses an image model to produce the edited result."},{q:"Can I edit a photo without design software?",a:"Yes. Pixel Shine runs in the browser and provides both a general AI editor and focused creative apps."}]},
 {slug:"ai-photo-generator",title:"AI Photo Generator Online | Pixel Shine",description:"Generate styled photos from your existing image with Pixel Shine AI photoshoot, portrait, headshot and creative apps.",h1:"AI Photo Generator Online",intro:"Start with an existing photo and create a new styled image without building the edit manually. Pixel Shine includes portrait, photoshoot, headshot and social generators.",appSlugs:["ai-photoshoot","ai-selfie-generator","professional-headshot","aesthetic-photo-editor","fashion-photo-editor","profile-picture-maker"],bullets:["Start from an existing photo","Generate portrait and photoshoot variations","Create professional or social styles","Download the generated result"],faqs:[{q:"How does an AI photo generator work?",a:"You provide a source image and choose a transformation. The AI uses the image and the app's instructions to produce a new visual."},{q:"Is Pixel Shine an image generator or editor?",a:"It supports both workflows: focused creative apps transform existing photos, while the broader AI editor can handle more open-ended edits."}]},
 {slug:"ai-headshot-generator",title:"AI Headshot Generator Online | Pixel Shine",description:"Create professional, LinkedIn, executive, doctor, lawyer and business headshots from a selfie.",h1:"AI Headshot Generator Online",intro:"Turn a clear selfie into a professional portrait with focused headshot apps for LinkedIn, business, executive and specialist profiles.",appSlugs:["ai-headshot-generator","linkedin-headshot","professional-headshot","ceo-headshot","doctor-headshot","lawyer-headshot"],bullets:["LinkedIn and professional profiles","Executive and corporate portraits","Doctor and lawyer profile photos","Multiple styles from the same starting photo"],faqs:[{q:"Can I create a headshot from a selfie?",a:"Yes. Upload a clear selfie to an AI headshot app and generate a professional portrait."},{q:"Which photo should I use?",a:"A front-facing, well-lit photo with a clear view of the face is usually the best starting point."}]},
 {slug:"remove-background",title:"AI Background Remover & Background Editor | Pixel Shine",description:"Remove, replace and generate image backgrounds with Pixel Shine's AI and browser tools.",h1:"AI Background Remover & Background Editor",intro:"Separate a subject from its background or create a new scene behind it. Use the focused background tools or continue into the AI editor.",appSlugs:["background-changer","remove-background","product-background-remover","product-background-generator","house-photo-editor"],bullets:["Remove distracting backgrounds","Replace a background with a new scene","Prepare product images","Continue into broader AI editing"],faqs:[{q:"Can I remove a background from a photo?",a:"Yes. Pixel Shine provides a dedicated background-removal workflow plus AI background editing options."},{q:"Can I replace the background too?",a:"Yes. Use the background changer or product background tools when you want a new scene rather than a transparent cutout."}]},
 {slug:"photo-enhancer",title:"AI Photo Enhancer & Image Quality Tools | Pixel Shine",description:"Sharpen, denoise, unblur, restore and enhance photos with Pixel Shine AI image-quality tools.",h1:"AI Photo Enhancer & Image Quality Tools",intro:"Improve an existing image before you publish, print or reuse it. Choose the tool based on whether the problem is blur, noise, age, softness or missing detail.",appSlugs:["ai-photo-enhancer","image-sharpener","unblur-image","denoise-image","restore-old-photos","old-photo-restoration"],bullets:["Sharpen soft photos","Reduce visible noise","Restore older images","Improve overall photo presentation"],faqs:[{q:"What is an AI photo enhancer?",a:"An AI photo enhancer uses image models to improve perceived detail, clarity or overall quality in an existing image."},{q:"Which tool should I use for a blurry image?",a:"Start with an unblur or image-sharpener workflow when the main issue is softness. For old damaged photos, use a restoration tool instead."}]},
 {slug:"photo-editor",title:"Online AI Photo Editor | Pixel Shine",description:"Edit photos online with AI creative apps for portraits, backgrounds, products, social media, restoration and more.",h1:"Online AI Photo Editor",intro:"Choose a focused editor instead of hunting through generic filters. Pixel Shine organizes AI photo editing by the result you want to create.",appSlugs:["ai-editor","ai-photoshoot","outfit-generator","background-changer","image-sharpener","profile-picture-maker"],bullets:["Portrait and photoshoot edits","Outfit and style changes","Background editing","Image enhancement and social content"],faqs:[{q:"What can I edit with Pixel Shine?",a:"You can edit portraits, outfits, backgrounds, image quality, profile pictures, products and many other photo use cases."},{q:"Do I need to install an app?",a:"No. Pixel Shine's tools run online in the browser."}]},
];

export function appsForPage(page: GrowthPage): CreativeApp[] {
 const seen=new Set<string>();
 return page.appSlugs.map(s=>CREATIVE_APPS.find(a=>a.slug===s)).filter((a):a is CreativeApp=>!!a && !seen.has(a.slug) && !!seen.add(a.slug));
}
