import dataset from "./dataset.json";
import type {
  Facet, Media, ModelInfo, PromptCardData, PromptRecord,
} from "./types";

/**
 * data.ts — every read of the prompt dataset goes through here.
 *
 * Server-only by construction: it imports a 1.8MB JSON, so a client component
 * that imported it would ship the entire library to the browser. Client
 * components take `PromptCardData[]` props instead, built by `toCard()`.
 *
 * The dataset is generated by scripts/build-prompt-dataset.mjs from the
 * licensed CC BY 4.0 export in data/. Attribution is not optional — see
 * `Attribution` in the UI and the footer credit line.
 */

interface Dataset {
  generatedAt: string;
  source: string;
  counts: {
    total: number; image: number; video: number;
    featured: number; withVariables: number; authors: number;
  };
  models: ModelInfo[];
  facets: Record<Media, { useCases: Facet[]; styles: Facet[]; subjects: Facet[] }>;
  records: PromptRecord[];
}

const DB = dataset as unknown as Dataset;

export const ALL: PromptRecord[] = DB.records;
export const COUNTS = DB.counts;
export const MODELS = DB.models;
export const FACETS = DB.facets;
export const GENERATED_AT = DB.generatedAt;

const BY_UID = new Map(ALL.map((r) => [r.uid, r]));
const BY_MODEL_SLUG = new Map(MODELS.map((m) => [m.slug, m]));

export function getPrompt(uid: string): PromptRecord | undefined {
  return BY_UID.get(uid);
}

export function getModel(slug: string): ModelInfo | undefined {
  return BY_MODEL_SLUG.get(slug);
}

/** `/prompts/…` for images, `/video-prompts/…` for video (spec §3). */
export function promptHref(r: Pick<PromptRecord, "uid" | "media">): string {
  return r.media === "video" ? `/video-prompts/${r.uid}` : `/prompts/${r.uid}`;
}

/**
 * The one image a card shows.
 *
 * Video records carry a poster frame instead of an images array, and four of
 * them carry neither — those fall through to the card's placeholder rather
 * than rendering a broken frame.
 */
export function cardImage(r: PromptRecord): string | null {
  if (r.media === "video") return r.videoThumbnail || r.images[0] || null;
  return r.images[0] || null;
}

/** Prompt text trimmed to something a card can show without shipping a novel. */
export function excerpt(r: PromptRecord, max = 240): string {
  const source = (r.description || r.prompt).replace(/\s+/g, " ").trim();
  return source.length <= max ? source : `${source.slice(0, max - 1).trimEnd()}…`;
}

export function toCard(r: PromptRecord): PromptCardData {
  return {
    uid: r.uid,
    title: r.title,
    excerpt: excerpt(r),
    model: r.model,
    modelSlug: r.modelSlug,
    media: r.media,
    featured: r.featured,
    image: cardImage(r),
    authorName: r.author.name,
    authorUrl: r.author.url,
    sourceUrl: r.sourceUrl,
    hasVariables: r.hasVariables,
    publishedAt: r.publishedAt,
    href: promptHref(r),
    useCase: r.useCase,
    needsPhoto: r.needsPhoto,
  };
}

export const toCards = (rs: PromptRecord[]): PromptCardData[] => rs.map(toCard);

// ── Selectors ───────────────────────────────────────────────────────────────

export function byMedia(media: Media): PromptRecord[] {
  return ALL.filter((r) => r.media === media);
}

export function byModel(slug: string): PromptRecord[] {
  return ALL.filter((r) => r.modelSlug === slug);
}

/** Records already arrive sorted by hotScore, so "hottest" is just the head. */
export function hottest(n: number, media?: Media): PromptRecord[] {
  const pool = media ? byMedia(media) : ALL;
  return pool.slice(0, n);
}

export function featured(n: number, media?: Media): PromptRecord[] {
  const pool = (media ? byMedia(media) : ALL).filter((r) => r.featured);
  return pool.slice(0, n);
}

export function newest(n: number, media?: Media): PromptRecord[] {
  const pool = media ? byMedia(media) : ALL;
  return [...pool]
    .sort((a, b) => (b.publishedAt || "").localeCompare(a.publishedAt || ""))
    .slice(0, n);
}

export type FacetKind = "use-cases" | "styles" | "subjects";

const FACET_FIELD: Record<FacetKind, "useCase" | "styles" | "subjects"> = {
  "use-cases": "useCase",
  styles: "styles",
  subjects: "subjects",
};

export function facetList(media: Media, kind: FacetKind): Facet[] {
  const f = FACETS[media];
  return kind === "use-cases" ? f.useCases : kind === "styles" ? f.styles : f.subjects;
}

/** Every facet of a medium, flattened — used to generate the category routes. */
export function allFacets(media: Media): { kind: FacetKind; facet: Facet }[] {
  const kinds: FacetKind[] = ["use-cases", "styles", "subjects"];
  return kinds.flatMap((kind) => facetList(media, kind).map((facet) => ({ kind, facet })));
}

export function findFacet(media: Media, slug: string): { kind: FacetKind; facet: Facet } | null {
  return allFacets(media).find((f) => f.facet.slug === slug) || null;
}

export function byFacet(media: Media, kind: FacetKind, name: string): PromptRecord[] {
  const field = FACET_FIELD[kind];
  return ALL.filter((r) => {
    if (r.media !== media) return false;
    const v = r[field];
    return Array.isArray(v) ? v.includes(name) : v === name;
  });
}

/**
 * Related prompts for a detail page.
 *
 * Same model first, because that is the comparison a reader is making, then
 * anything sharing a use case. Never the prompt itself.
 */
export function related(r: PromptRecord, n = 6): PromptRecord[] {
  const sameModel = ALL.filter((x) => x.uid !== r.uid && x.model === r.model);
  const sameUse = ALL.filter(
    (x) => x.uid !== r.uid && x.model !== r.model && x.useCase && x.useCase === r.useCase
  );
  return [...sameModel, ...sameUse].slice(0, n);
}

// ── Variables (spec §2) ─────────────────────────────────────────────────────

/*
  Re-exported, not defined here: the chip editor is a client component and
  this module imports the whole dataset, which must never follow it into the
  browser bundle. lib/prompts/variables.ts is the shared implementation.
*/
export { parseVariables, fillVariables } from "./variables";

// ── Search ──────────────────────────────────────────────────────────────────

/**
 * Substring search over title, description, model, author and tags.
 *
 * Not over the full prompt text: a 22,000-character prompt matches almost any
 * word, which buries the records that are actually about the thing searched
 * for. The first 400 characters are enough to catch the subject.
 */
export function search(query: string, pool: PromptRecord[] = ALL): PromptRecord[] {
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  const terms = q.split(/\s+/).filter(Boolean);
  return pool.filter((r) => {
    const hay = [
      r.title, r.description || "", r.model, r.author.name,
      r.useCase || "", r.styles.join(" "), r.subjects.join(" "),
      r.prompt.slice(0, 400),
    ].join(" ").toLowerCase();
    return terms.every((t) => hay.includes(t));
  });
}
